
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId:
            clientSecret:
            scope:
              - gist
              - user


              